#!/usr/bin/env ruby

require 'tmpdir'
require 'fileutils'

# Test script to verify write_to_repo functionality
lib_path = File.join(File.dirname(__FILE__), 'lib')
$LOAD_PATH.unshift(lib_path)

require 'git_template/generator/base'

# Load the example generator
load 'templated/examples/rails8-simple/.git_template/template_part/gem_file_generator_0001.rb'

# Test config
class TestConfig
  attr_reader :id
  def initialize(id = 'test-123')
    @id = id
  end
end

puts "=== write_to_repo Test ==="
puts

# Test in a temp directory
Dir.mktmpdir do |tmpdir|
  puts "Testing in: #{tmpdir}"
  
  config = TestConfig.new
  generator = GemFileGenerator0001.new(config)
  
  # Test write_to_repo
  result = generator.write_to_repo(base_path: tmpdir)
  
  puts "✓ File created at: #{result}"
  
  # Verify file exists
  if File.exist?(result)
    puts "✓ File exists"
  else
    raise "File not created"
  end
  
  # Verify content
  content = File.read(result)
  
  if content.include?("Generated by:")
    puts "✓ Metadata header present"
  else
    raise "Missing metadata header"
  end
  
  if content.include?('gem "rails"')
    puts "✓ Golden text content present"
  else
    raise "Missing golden text"
  end
  
  # Show first few lines
  puts
  puts "First 10 lines of generated file:"
  puts "-" * 60
  puts content.lines.first(10).join
  puts "-" * 60
  
  # Test without metadata
  result2 = generator.write_to_repo(include_metadata: false, base_path: tmpdir)
  content2 = File.read(result2)
  
  if !content2.include?("Generated by:")
    puts "✓ No metadata when include_metadata: false"
  else
    raise "Metadata present when it shouldn't be"
  end
  
  puts
  puts "=== All Tests Passed ==="
end
